# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  solution: '**/CICD.Api.1.sln'
  project: '**/CICD.Api.1.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nuget Tool Installer'
- task: NuGetCommand@2
  name: 'NugetRestore'
  displayName: 'Nuget restore packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    modifyOutputPath: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: 'PublishArtifact'
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AzureTestProject'
    publishLocation: 'Container'